#!/bin/bash

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Get colors from .Xresources -------------------------------#
focused=$(xrdb ~/.Xresources -query all | grep color6 | cut -f2 | head -n 1)
normal=$(xrdb ~/.Xresources -query all | grep background | cut -f2 | head -n 1)

## Configurations -------------------------------#

lc=$(xrandr | grep " connected" | wc -l)
echo $lc
if [ $lc = "1" ]
then
    xrandr --output eDP-1 --mode 1920x1080 --output DP1 --off
    bspc monitor eDP-1 -d I II III IV V VI VII VIII IX 
else
    xrandr --output DP1 --primary --mode 1920x1080 --rotate normal --output eDP-1 --mode 1920x1080 --rotate normal --below DP1
    bspc monitor DP1 -d I II III IV V
    bspc monitor eDP-1 -d VI VII VIII IX 
fi





bspc config border_width 1
bspc config window_gap 6
bspc config split_ratio 0.50

bspc config focused_border_color "$focused" 
bspc config normal_border_color "$normal"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1


sysresources=$HOME/.config/.Xresources
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi


## Window rules -------------------------------#

#google-chrome-unstable = Google-chrome-unstable
#celluloid = Io.github.celluloid_player.Celluloid
#qbittorrent = qBittorent
#




# remove all rules first
bspc rule -r *:*

# 1 > home
bspc rule -a Termite desktop='^5' state=tiled focus=on manage=on
bspc rule -a Xfce4-terminal desktop='^5' state=tiled focus=on manage=on
# 2 > web
bspc rule -a 'Firefox Beta'desktop='^3' follow=on focus=on
bspc rule -a Xfce4-appfinder state=floating follow=on focus=on
bspc rule -a Brave-browser desktop='^3' follow=on focus=on
bspc rule -a Google-chrome-unstable desktop='^3' follow=on
bspc rule -a Transmission-gtk desktop='^8'
bspc rule -a persepolis desktop='^8' 
bspc rule -a MEGAsync desktop='^8' state=floating rectangle=100x100+1500+500
bspc rule -a TelegramDesktop desktop='^9' follow=on
bspc rule -a discord split_ratio=.40 desktop='^9' follow=on
bspc rule -a Stremio split_ratio=0.35 desktop='^7' follow=on
bspc rule -a okular split_ratio=.25 desktop='^4' follow=on focus=on
bspc rule -a zoom desktop='^2' follow=on
bspc rule -a 'Free Download Manager' desktop='^8' 
#bspc rule -a mpv desktop='^7' state=fullscreen follow=on focus=on
bspc rule -a mpv state=floating 
bspc rule -a qutebrowser desktop='^3' follow=on focus=on
bspc rule -a Subl3 desktop='^2' follow=on focus=on


# 3 > file
#bspc rule -a  desktop='^3' follow=on focus=on
# 4 > work


# 5 > video
#declare -a media=(names)
#for i in ${media[@]}; do
#   bspc rule -a $i desktop='^7' state=fullscreen follow=on focus=on; done

# 6 > book
#7 > media
#8 > downloadscenter=true rectangle=1376x625+0+0

#bspc rule -a qBittorrent desktop='^8'state=floating focus=on manage=on
#bspc rule -a persepolis desktop='^8'state=floating focus=on manage=on

#bspc rule -a MEGAsync desktop='^8'state=floating focus=on manage=on

#9 > extra


# special rules

bspc rule -a Firefox:Places state=floating follow=on focus=on




#bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------#

# Kill if already running
killall -9 mpd dunst sxhkd pcmanfm xsettingsd dunst xfce4-power-manager qbittorrent megasync persepolis firefox-beta stremio google-chrome-unstable thunar transmission-gtk kdeconnect-cli



# Lauch notification daemon

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
bash $HOME/.fehbg 

# Start mpd


# Start bspwm scripts
#bspcolors
#bspcomp
#bspbar &

bspbar &
bspcomp


mpd &



#Autostart
numlockx &
fdm &
dunst &
pcmanfm --daemon&
kdeconnect-cli &
#telegram-desktop &
#discord &
transmission-gtk &
optimus-manager-qt &
megasync &
