#!/bin/bash

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Get colors from .Xresources -------------------------------#
focused=$(xrdb ~/.Xresources -query all | grep color6 | cut -f2 | head -n 1)
normal=$(xrdb ~/.Xresources -query all | grep background | cut -f2 | head -n 1)

## Configurations -------------------------------#

lc=$(xrandr | grep " connected" | wc -l)
echo $lc
if [ $lc = "1" ]
then
    xrandr --output eDP-1 --mode 1920x1080 --output DP1 --off
    bspc monitor eDP-1 -d I II III IV V VI VII VIII IX
else
    xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-1 --mode 1366x768 --pos 1920x0 --rotate normal
    bspc monitor eDP-1 -d I II III IV 
    bspc monitor HDMI-1 -d V VI VII VIII IX
fi



bspc config border_width 1
bspc config window_gap 6
bspc config split_ratio 0.50

bspc config focused_border_color "$focused" 
bspc config normal_border_color "$normal"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1


sysresources=$HOME/.config/.Xresources
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi


## Window rules -------------------------------#

# remove all rules first
bspc rule -r *:*

# 2 > web
bspc rule -a 'Firefox' desktop='^2' follow=on focus=on
bspc rule -a Transmission-gtk desktop='^9' follow=off focus=off
bspc rule -a Stremio split_ratio=0.35 desktop='^7' follow=on
bspc rule -a okular split_ratio=.25 desktop='^4' follow=on focus=on
bspc rule -a zoom desktop='^2' follow=on
bspc rule -a 'Free Download Manager' desktop='^9' follow=off focus=off
bspc rule -a mpv state=floating 
bspc rule -a qutebrowser desktop='^3' follow=on focus=on
bspc rule -a Pavucontrol state=floating 
bspc rule -a Kite desktop='^2' split_ratio=0.80


## Autostart -------------------------------#

# Kill if already running
killall -9 mpd udiskie dunst sxhkd pcmanfm xsettingsd dunst  megasync  stremio  transmission-gtk kdeconnect-cli



# Lauch notification daemon

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &


# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
bash $HOME/.fehbg 


# Start bspwm scripts
#bspcolors

bspbar &
bspcomp &

udiskie -At &


mpd &

#Autostart
numlockx &
fdm &
dunst &
kdeconnect-cli &
transmission-gtk &
optimus-manager-qt &
megasync &
